language:
  - java
  - c++
  - python
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  # bazel
  - wget https://github.com/bazelbuild/bazel/archive/0.4.5.zip  # Replace with desired version
  - unzip 0.4.5.zip
  - cd bazel-0.4.5
  - ./compile.sh
  - sudo cp output/bazel /usr/bin/bazel
  - cd ..
  - rm -rf bazel-0.4.5
  # numpy
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda install --yes numpy=1.8
  # setup python
  - ./setup

script:
  - bazel build //...
  - bazel test //...
