dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

language:
  - java
  - c++
  - python

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - wget
#       - pkg-config


before_install:
  # debug
  - pwd # check current dir, result: /home/travis/build/yuikns/argcv
  - echo $PATH
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                                                         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew upgrade                                                                   ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python3                                                                ; fi
  # - wget https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-installer-linux-x86_64.sh -O bazel-installer.sh
  # - chmod +x bazel-installer.sh
  # - sudo ./bazel-installer.sh # require javac
  # - sudo rm -rf bazel-installer.sh
  # install bazel
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel_0.4.5-linux-x86_64.deb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i bazel_0.4.5-linux-x86_64.deb                                                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bazel                                                                              ; fi
  # numpy
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/mc # require: bzip2, tar  command with path: ./miniconda.sh -b -p /home/travis/mc
  - rm -rf miniconda.sh
  - export PATH=$HOME/mc/bin:$PATH
  - conda install --yes numpy # current is 1.12.1-py36_0

script:
  # setup python
  - ./setup
  - bazel build //...
  - bazel test //...
