dist: trusty
sudo: required

# temp disable cache
cache:
  directories:
   - $HOME/mc
   - $HOME/.cache

compiler:
  - gcc
  - clang

language:
  - java
  - c++
  - python


# JDK configuration, ref: https://github.com/travis-ci/travis-ci/issues/2316
matrix:
  include:
    - os: linux
      jdk: oraclejdk8  # Building Bazel requires JDK8.
    - os: osx
      osx_image: xcode8  # Building Bazel requires JDK8.


# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - wget
#       - pkg-config


before_install:
  # debug
  - pwd # check current dir, result: /home/travis/build/yuikns/argcv
  - . .travis/before_install.sh
  - echo $PATH

script:
  # setup python
  - ./setup
  - bazel build //...
  - bazel test //...
