dist: trusty
sudo: required

# temp disable cache
cache:
  directories:
   - $HOME/mc
   - $HOME/.cache/bazel

compiler:
  - gcc
  - clang

language:
  - java
  - c++
  - python


# JDK configuration, ref: https://github.com/travis-ci/travis-ci/issues/2316
matrix:
  include:
    - os: linux
      jdk: oraclejdk8  # Building Bazel requires JDK8.
      env:
        - CACHE_NAME=linux
    - os: osx
      osx_image: xcode8  # Building Bazel requires JDK8.
      env:
        - CACHE_NAME=osx

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - wget
#       - pkg-config

before_install:
  # debug
  - . .travis/before_install.sh
  - pwd # check current dir, result: /home/travis/build/yuikns/argcv
  - echo $PATH
  - df -h
  - date
  - uname -a
  # - python -v

install:
  - . .travis/install.sh
  - echo $PATH

script:
  # setup python
  - ./setup
  - bazel fetch //...
  # build by stage for cache
  - bazel build examples/cxx:hello_world
  - bazel build examples/grpc/protos:helloworld
  - bazel build examples/grpc/cxx/helloworld:greeter_async_server
  - bazel build //...
  - bazel test //...
