#!/bin/sh
CC_SCRIPT_FILE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/cpplint.py
if (($# == 0 )); then
    find .  -name '*.cc' -o -name '*.c' -o -name '*.h' -o -name '*.hh' -o -name '*.C' -o -name '*.cpp' -o -name '*.hpp' -o -name '*.H' | xargs python $CC_SCRIPT_FILE --extensions=hh,cc,c,h
else
    find $1  -name '*.cc' -o -name '*.c' -o -name '*.h' -o -name '*.hh' -o -name '*.C' -o -name '*.cpp' -o -name '*.hpp' -o -name '*.H' | xargs python $CC_SCRIPT_FILE --extensions=hh,cc,c,h
fi
